name: coUserver
version: 0.0.0
author: coU Development Team
description: The sourcecode/tools needed to hack/compile the Children of Ur server
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  redstone:
    path: ../vendor/redstone
  redstone_mapper_pg:
    path: ../vendor/redstone_mapper_pg
  intl: "^0.15.8"
  http: "^0.11.3+3"
  slack:
    path: ../vendor/dart-slack
  image: "^2.1.19"
  message_bus:
    path: ../vendor/message_bus
  jsonx:
    path: ../vendor/jsonx
  inflection:
    path: ../vendor/inflection
  args: "^1.5.2"

